### ISSUE TITLE
x11-drivers/amdgpu-pro - how does it work? 

### ISSUE THREAD

**Issue by stefson** [sandikata/ROKO__#19]
hey there, I found your ebuilds of amdgpu-pro by pure chance. I bought a rx 550 just to find out later on that these have a different chipset than the rx 560/70/80 and thus are not yet fully supported from the linux kernel. 

Have you emerged your amdgpu-pro ebuild with success in terms of being able to use a normal graphical desktop environement, and prefereable with 3d-acceleration? I mean, can I use my normal xorg-server-1.19, is there anything I have to take care of about the kernel, do I need a special xorg.conf, etc.? 

ah yeah, and the 17.50-* ebuild doesn't work because of path confusion :)

**Comment by sandikata** [comment]
Hello! So at the moment i'm so bussy, and there will be unexpected delay.
amdgpu-pro can be used for legacy cards if CIK and SIK support is enabled.
AMD have enabled this legacy support since version 16 i think.
About xorg server, check Ubuntu 16.04. AMD stuck on this ubuntu version for some reason.

**Comment by sandikata** [comment]
At the moment.. I am not able to fix it, i still looking for solution, but there is not enough info.
