### ISSUE TITLE
CachyOS 6.3 is broken with latency patch

### ISSUE THREAD

**Issue by Szowisz** [sandikata/ROKO__#35]
6.3 kernel is not compatible with latency fix patch. It fails to install if this patch is used. 
Also please add bore+eevdf.

**Comment by sandikata** [comment]
bore+eevdf is not compatible for use together, ask upstream for that.

Mostly i am disappointed by 6.3 series of cachyos patch set, it's so broken.
It may corrupt your btrfs partitions (with no obvious reason), also to KP when using VirtualBox.

I've reported these issues to the upstream, they just send me to /dev/null, literally.
As they said, not issues from our side, it works perfect.

As long as their behavior is like that. I am not about to push any updates here. Even me using default gentoo-sources right now.

The only i can do is to remove latency fix patch (but it is not broken because of it, it is just not compatible with eevdf patch, as eevdf provides same functionality). You can use latency patch only with BORE.

**Comment by Szowisz** [comment]
This is just what I did (bore+latency) but it won't work, it is not compatible with 6.3 kernel even with bore. 
![IMG_0324](https://github.com/sandikata/ROKO__/assets/77622670/331ee63d-f1ef-4608-8627-ea4f4b6a06b0)

**Comment by Szowisz** [comment]
And there is eevdf+bore: https://github.com/CachyOS/kernel-patches/blob/master/6.3/sched/0001-bore-eevdf.patch

**Comment by Szowisz** [comment]
Anyway thanks for help :) Just remove latency patch and it should work

**Comment by sandikata** [comment]
> And there is eevdf+bore: https://github.com/CachyOS/kernel-patches/blob/master/6.3/sched/0001-bore-eevdf.patch

I know, but try to apply it (it will fail 100%).

I will review latency patch once again.

**Comment by Szowisz** [comment]
Ok, I didn't know. For sure I will try build it 😀

**Comment by ptr1337** [comment]
> bore+eevdf is not compatible for use together, ask upstream for that.
> 
> Mostly i am disappointed by 6.3 series of cachyos patch set, it's so broken. It may corrupt your btrfs partitions (with no obvious reason), also to KP when using VirtualBox.
> 
> I've reported these issues to the upstream, they just send me to /dev/null, literally. As they said, not issues from our side, it works perfect.
> 
> As long as their behavior is like that. I am not about to push any updates here. Even me using default gentoo-sources right now.
> 
> The only i can do is to remove latency fix patch (but it is not broken because of it, it is just not compatible with eevdf patch, as eevdf provides same functionality). You can use latency patch only with BORE.

I don't know what you are talking about. You never reported to us ANY issue and no user has reported BTRFS corruption so far. You also don't made a issue with logs related to this.

Also the information you are spreading are wrong. BORE-EEVDF is working since 6.3.1 and is also used by us.
It was only for the initial 6.3 release not working, so please keep your information's updated before spreading them or ask us.

Here you can find all used patches and which are working. All are tested and compiled by our repo.
https://github.com/CachyOS/linux-cachyos/blob/master/linux-cachyos/PKGBUILD#L243-L259
We can't handle issues, which are related to gentoo or your ebuild.

**Comment by ptr1337** [comment]
And related to latency nice:
Latency Nice is included as default in the 0001-EEVDF.patch, since EEVDF depends on it but has a own version for. I was in contact with the author of the latency-nice patchset and he won't update latency-nice for 6.3, because of the EEVDF development.
So feel free to adjust the patch, that it will work with 6.3 and do a PR.

**Comment by sandikata** [comment]
> > bore+eevdf is not compatible for use together, ask upstream for that.
> > Mostly i am disappointed by 6.3 series of cachyos patch set, it's so broken. It may corrupt your btrfs partitions (with no obvious reason), also to KP when using VirtualBox.
> > I've reported these issues to the upstream, they just send me to /dev/null, literally. As they said, not issues from our side, it works perfect.
> > As long as their behavior is like that. I am not about to push any updates here. Even me using default gentoo-sources right now.
> > The only i can do is to remove latency fix patch (but it is not broken because of it, it is just not compatible with eevdf patch, as eevdf provides same functionality). You can use latency patch only with BORE.
> 
> I don't know what you are talking about. You never reported to us ANY issue and no user has reported BTRFS corruption so far. You also don't made a issue with logs related to this.
> 
> Also the information you are spreading are wrong. BORE-EEVDF is working since 6.3.1 and is also used by us. It was only for the initial 6.3 release not working, so please keep your information's updated before spreading them or ask us.
> 
> Here you can find all used patches and which are working. All are tested and compiled by our repo. https://github.com/CachyOS/linux-cachyos/blob/master/linux-cachyos/PKGBUILD#L243-L259 We can't handle issues, which are related to gentoo or your ebuild.

That's what i mean, you never admitted anything.
Just telling "it works". So i lost interest to waste my time of debugging.

Last time when i reported the issue with Virtualbox and btrfs you just said, it works perfect with VMs.

**Comment by Szowisz** [comment]
> Ok, I didn't know. For sure I will try build it grinning

It works.  Maybe you did something wrong? You need both eevdf and bore-eevdf patches (and apply it in the order listed above). This is what my ebuild looks like (for 6.3.4 and with removed latency patch): https://pastebin.com/CDWg50ip

**Comment by sandikata** [comment]
> > Ok, I didn't know. For sure I will try build it grinning
> 
> It works. Maybe you did something wrong? You need both eevdf and bore-eevdf patches (and apply it in the order listed above). This is what my ebuild looks like (for 6.3.4 and with removed latency patch): https://pastebin.com/CDWg50ip

I tried that on 6.3.3 but didn't work either.

Your ebuild doesn't work at all.
Anyway, i stopped any development of these ebuilds.

**Comment by Szowisz** [comment]
> Your ebuild doesn't work at all. Anyway, i stopped any development of these ebuilds.

What is wrong with my ebuild?

Regards :)

**Comment by sandikata** [comment]
Maybe it worked somehow for you, but anyway it fails on patch apply (eevdf, eevdf-bore).
As i said, moved to xanmod. You are free to create PR for cachyos-sources, i will merge them. But i lost interest to develop it on my own.

Regards.

**Comment by ptr1337** [comment]
> Maybe it worked somehow for you, but anyway it fails on patch apply (eevdf, eevdf-bore). As i said, moved to xanmod. You are free to create PR for cachyos-sources, i will merge them. But i lost interest to develop it on my own.
> 
> Regards.

Everything, you can remove it from your repository. We have a new maintainer and it is working fine :)

**Comment by sandikata** [comment]
I have no problem with that. If it "working fine" for you. Then it is fine.
I said early why i've decided to stop development.
BTRFS breakage with 6.3 patch set (i know, you'll say again, it works fine for me. My response is → it doesn't happen on any other 6.3 kernel patches or vanilla one). 

I do respect your work on this, but i do not respect ignorance on the real issues. :)

Regards.
